version: "3.8"
services:

  #    marketplace:
  #        build:
  #            context: .
  #            dockerfile: marketplace/Dockerfile
  #        environment:
  #            RECOMMENDATIONS_HOST: recommendations
  #        image: marketplace
  #        networks:
  #            - microservices
  #        ports:
  #            - 5000:5000

    server:
        build:
            context: .
            dockerfile: server/Dockerfile
        image: server
        networks:
            - microservices

networks:
    microservices:
